services:
  - type: web
    name: auiv-tracker-api
    runtime: python
    repo: https://github.com/Nandostream11/auiv-tracker-app
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://REDACTED_DB_USER:REDACTED_PASSWORD@REDACTED_CLUSTER_HOST/?appName=auiv-cluster
      - key: DB_NAME
        value: auiv_tracker
      - key: PYTHON_VERSION
        value: "3.12.0"
    healthCheckPath: /health
    autoDeploy: true
    plan: free
